# This a template for the application-secure.yml file that must be created and configured in order
# to be able to execute the application. The necessary steps are the following:
#
#   1. Copy this file and rename the copy to application-secure.yml
#   2. Replace {DATABASE_NAME} with the application database name
#   3. Replace {DATABASE_USER} with the application database user's username
#   4. Replace {DATABASE_NAME} with the application database user's password
#   5. Delete this comments block
#   6. Add the comment 'DO NOT COMMIT THIS FILE!' to the first line of the file
#
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/{DATABASE_NAME}
    username: {DATABASE_USER}
    password: {DATABASE_NAME}
