app:
  integration:
    coin-cap:
      base-url: https://api.coincap.io/v2
  scheduler:
    token:
      update-interval: 1800000

logging:
  file:
    # The file name is left empty to keep the logs only in the console
    name: ""
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

server:
  port: 8083

spring:
  application:
    name: coincap-code-challenge
  config:
    import: classpath:application-secure.yml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      maximum-pool-size: 10
      minimum-idle: 5
      pool-name: CoinCapPool

  flyway:
    enabled: true
    locations: classpath:db/migration/ddl, classpath:db/migration/dml

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate.format_sql: true
      hibernate.use_sql_comments: true
    show-sql: true
